import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AudioLines,
  BatteryCharging,
  CalendarDays,
  Car,
  CloudSun,
  HeartPulse,
  Newspaper,
  Sparkles,
} from "lucide-react";
import { toast } from "sonner";
import { useEffect, useState } from "react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { HudCard } from "@/components/hud/hud-card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { getSettings, updateSettings, previewVoice } from "@/lib/briefing.functions";
import { useServerFn } from "@tanstack/react-start";
import { Loader2 } from "lucide-react";

export const Route = createFileRoute("/_authenticated/settings")({
  component: SettingsPage,
});

const toggles = [
  {
    key: "include_weather",
    label: "Weather",
    desc: "Today's forecast for your location.",
    icon: CloudSun,
  },
  {
    key: "include_traffic",
    label: "Traffic",
    desc: "Live drive time from your commute origin to destination, scraped from Google Maps (with current traffic).",
    icon: Car,
  },
  {
    key: "include_calendar",
    label: "Google Calendar",
    desc: "Today's meetings and time blocks.",
    icon: CalendarDays,
  },
  {
    key: "include_whoop",
    label: "Whoop recovery",
    desc: "Recovery, HRV, and strain targets.",
    icon: HeartPulse,
  },
  {
    key: "include_batteries",
    label: "Device batteries",
    desc: "Phone, watch, earbuds and peripherals.",
    icon: BatteryCharging,
  },
  {
    key: "include_roca_news",
    label: "AI news digest",
    desc: "Personalized news brief generated by AI from your topics of interest.",
    icon: Newspaper,
  },
] as const;

const voices = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"] as const;

function SettingsPage() {
  const qc = useQueryClient();
  const { data, isLoading } = useQuery({
    queryKey: ["settings"],
    queryFn: () => getSettings(),
  });
  type SettingsPatch = Partial<{
    include_calendar: boolean;
    include_whoop: boolean;
    include_batteries: boolean;
    include_roca_news: boolean;
    include_weather: boolean;
    include_traffic: boolean;
    weather_location: string;
    traffic_origin: string;
    traffic_destination: string;
    news_topics: string;
    custom_instructions: string;
    text_to_speech_enabled: boolean;
    voice: (typeof voices)[number];
  }>;
  const mut = useMutation({
    mutationFn: (input: SettingsPatch) => updateSettings({ data: input }),
    onMutate: async (input) => {
      await qc.cancelQueries({ queryKey: ["settings"] });
      const prev = qc.getQueryData(["settings"]);
      qc.setQueryData(["settings"], (old: typeof data) =>
        old ? { ...old, ...input } : old,
      );
      return { prev };
    },
    onError: (e, _v, ctx) => {
      if (ctx?.prev) qc.setQueryData(["settings"], ctx.prev);
      toast.error(e instanceof Error ? e.message : "Update failed");
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["settings"] }),
  });

  const previewFn = useServerFn(previewVoice);
  const [previewingVoice, setPreviewingVoice] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  async function handleVoiceChange(v: (typeof voices)[number]) {
    mut.mutate({ voice: v });
    try {
      setPreviewingVoice(v);
      const res = await previewFn({ data: { voice: v } });
      const src = `data:${res.mime};base64,${res.audio_base64}`;
      if (audioRef.current) {
        audioRef.current.pause();
      }
      const a = new Audio(src);
      audioRef.current = a;
      a.onended = () => setPreviewingVoice((cur) => (cur === v ? null : cur));
      await a.play();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Voice preview failed");
      setPreviewingVoice(null);
    }
  }


  return (
    <div className="space-y-6">
      <HudCard eyebrow="Briefing modules" title="Toggle data sources">
        {isLoading || !data ? (
          <div className="h-32 animate-pulse rounded bg-secondary/40" />
        ) : (
          <div className="grid gap-3">
            {toggles.map((t) => {
              const Icon = t.icon;
              const checked = Boolean(data[t.key]);
              return (
                <label
                  key={t.key}
                  className="flex items-center justify-between gap-4 rounded-md border border-border/60 bg-background/40 p-3 transition hover:border-hud/30"
                >
                  <div className="flex items-start gap-3">
                    <div className="flex h-8 w-8 items-center justify-center rounded-md border border-border/60 bg-secondary/60">
                      <Icon className="h-4 w-4 text-hud" />
                    </div>
                    <div>
                      <div className="text-sm font-medium">{t.label}</div>
                      <div className="text-xs text-muted-foreground">{t.desc}</div>
                    </div>
                  </div>
                  <Switch
                    checked={checked}
                    onCheckedChange={(v) => mut.mutate({ [t.key]: v })}
                  />
                </label>
              );
            })}
            {data?.include_weather ? (
              <TextSettingInput
                label="Weather location"
                hint="City or 'City, State'. Example: Austin, TX or Brooklyn, NY."
                placeholder="Austin, TX"
                initial={data.weather_location ?? ""}
                onSave={(v) => mut.mutate({ weather_location: v })}
              />
            ) : null}
            {data?.include_traffic ? (
              <div className="grid gap-3 sm:grid-cols-2">
                <TextSettingInput
                  label="Commute origin"
                  hint="Home address or area."
                  placeholder="123 Main St, Austin, TX"
                  initial={data.traffic_origin ?? ""}
                  onSave={(v) => mut.mutate({ traffic_origin: v })}
                />
                <TextSettingInput
                  label="Commute destination"
                  hint="Office or first stop."
                  placeholder="500 Congress Ave, Austin, TX"
                  initial={data.traffic_destination ?? ""}
                  onSave={(v) => mut.mutate({ traffic_destination: v })}
                />
              </div>
            ) : null}
            {data?.include_roca_news ? <NewsTopicsInput initial={data.news_topics ?? ""} onSave={(v) => mut.mutate({ news_topics: v })} /> : null}
          </div>
        )}
      </HudCard>

      <HudCard
        eyebrow="AI refinement"
        title="Custom instructions"
        actions={<Sparkles className="h-4 w-4 text-hud" />}
      >
        {data && (
          <CustomInstructionsInput
            initial={data.custom_instructions ?? ""}
            onSave={(v) => mut.mutate({ custom_instructions: v })}
          />
        )}
      </HudCard>

      <HudCard eyebrow="Audio synthesis" title="Text-to-speech">
        {data && (
          <div className="space-y-4">
            <label className="flex items-center justify-between gap-4 rounded-md border border-border/60 bg-background/40 p-3">
              <div className="flex items-start gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-md border border-border/60 bg-secondary/60">
                  <AudioLines className="h-4 w-4 text-hud" />
                </div>
                <div>
                  <div className="text-sm font-medium">Generate audio</div>
                  <div className="text-xs text-muted-foreground">
                    Synthesize each briefing into an MP3 for Sonos playback.
                  </div>
                </div>
              </div>
              <Switch
                checked={Boolean(data.text_to_speech_enabled)}
                onCheckedChange={(v) => mut.mutate({ text_to_speech_enabled: v })}
              />
            </label>

            <div className="flex items-center justify-between gap-4 rounded-md border border-border/60 bg-background/40 p-3">
              <div>
                <Label className="text-sm font-medium">Voice</Label>
                <div className="text-xs text-muted-foreground">Default narration voice.</div>
              </div>
              <Select
                value={data.voice ?? "alloy"}
                onValueChange={(v) => mut.mutate({ voice: v as (typeof voices)[number] })}
              >
                <SelectTrigger className="w-40">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {voices.map((v) => (
                    <SelectItem key={v} value={v} className="capitalize">
                      {v}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        )}
      </HudCard>
    </div>
  );
}

function NewsTopicsInput({ initial, onSave }: { initial: string; onSave: (v: string) => void }) {
  const [value, setValue] = useState(initial);
  useEffect(() => setValue(initial), [initial]);
  return (
    <div className="rounded-md border border-border/60 bg-background/40 p-3">
      <Label className="text-sm font-medium">Your news topics</Label>
      <div className="text-xs text-muted-foreground mb-2">
        Comma-separated. Examples: AI industry, NBA, climate policy, Austin TX, F1.
      </div>
      <Input
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onBlur={() => value !== initial && onSave(value)}
        placeholder="AI, markets, NBA, my city…"
      />
    </div>
  );
}

function CustomInstructionsInput({
  initial,
  onSave,
}: {
  initial: string;
  onSave: (v: string) => void;
}) {
  const [value, setValue] = useState(initial);
  useEffect(() => setValue(initial), [initial]);
  const dirty = value !== initial;
  return (
    <div className="space-y-3 rounded-md border border-border/60 bg-background/40 p-3">
      <div>
        <Label className="text-sm font-medium">Refine how Maverick speaks to you</Label>
        <div className="text-xs text-muted-foreground mt-1">
          Free-form instructions appended to every briefing prompt. Examples: "Keep it under 4
          sentences", "Be sarcastic and concise", "Always end with a workout suggestion", "Skip
          weather, lead with my first meeting".
        </div>
      </div>
      <Textarea
        value={value}
        onChange={(e) => setValue(e.target.value)}
        rows={5}
        maxLength={2000}
        placeholder="Tell Maverick how you want the briefing tailored…"
      />
      <div className="flex items-center justify-between">
        <span className="mono text-[10px] uppercase tracking-wider text-muted-foreground">
          {value.length} / 2000
        </span>
        <Button
          size="sm"
          variant={dirty ? "default" : "secondary"}
          disabled={!dirty}
          onClick={() => onSave(value)}
        >
          Save instructions
        </Button>
      </div>
    </div>
  );
}

function TextSettingInput({
  label,
  hint,
  placeholder,
  initial,
  onSave,
}: {
  label: string;
  hint?: string;
  placeholder?: string;
  initial: string;
  onSave: (v: string) => void;
}) {
  const [value, setValue] = useState(initial);
  useEffect(() => setValue(initial), [initial]);
  return (
    <div className="rounded-md border border-border/60 bg-background/40 p-3">
      <Label className="text-sm font-medium">{label}</Label>
      {hint && <div className="text-xs text-muted-foreground mb-2">{hint}</div>}
      <Input
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onBlur={() => value !== initial && onSave(value)}
        placeholder={placeholder}
      />
    </div>
  );
}

