/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicIngestBatteriesRouteImport } from './routes/api/public/ingest/batteries'
import { Route as ApiPublicOauthWhoopCallbackRouteImport } from './routes/api/public/oauth/whoop/callback'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google/callback'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIngestBatteriesRoute =
  ApiPublicIngestBatteriesRouteImport.update({
    id: '/api/public/ingest/batteries',
    path: '/api/public/ingest/batteries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthWhoopCallbackRoute =
  ApiPublicOauthWhoopCallbackRouteImport.update({
    id: '/api/public/oauth/whoop/callback',
    path: '/api/public/oauth/whoop/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google/callback',
    path: '/api/public/oauth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/ingest/batteries': typeof ApiPublicIngestBatteriesRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/whoop/callback': typeof ApiPublicOauthWhoopCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/ingest/batteries': typeof ApiPublicIngestBatteriesRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/whoop/callback': typeof ApiPublicOauthWhoopCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/support': typeof SupportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/ingest/batteries': typeof ApiPublicIngestBatteriesRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/whoop/callback': typeof ApiPublicOauthWhoopCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/signin'
    | '/support'
    | '/dashboard'
    | '/integrations'
    | '/logs'
    | '/settings'
    | '/api/public/ingest/batteries'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/whoop/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/signin'
    | '/support'
    | '/dashboard'
    | '/integrations'
    | '/logs'
    | '/settings'
    | '/api/public/ingest/batteries'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/whoop/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/privacy'
    | '/signin'
    | '/support'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/logs'
    | '/_authenticated/settings'
    | '/api/public/ingest/batteries'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/whoop/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SupportRoute: typeof SupportRoute
  ApiPublicIngestBatteriesRoute: typeof ApiPublicIngestBatteriesRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
  ApiPublicOauthWhoopCallbackRoute: typeof ApiPublicOauthWhoopCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ingest/batteries': {
      id: '/api/public/ingest/batteries'
      path: '/api/public/ingest/batteries'
      fullPath: '/api/public/ingest/batteries'
      preLoaderRoute: typeof ApiPublicIngestBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/whoop/callback': {
      id: '/api/public/oauth/whoop/callback'
      path: '/api/public/oauth/whoop/callback'
      fullPath: '/api/public/oauth/whoop/callback'
      preLoaderRoute: typeof ApiPublicOauthWhoopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/callback': {
      id: '/api/public/oauth/google/callback'
      path: '/api/public/oauth/google/callback'
      fullPath: '/api/public/oauth/google/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SupportRoute: SupportRoute,
  ApiPublicIngestBatteriesRoute: ApiPublicIngestBatteriesRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
  ApiPublicOauthWhoopCallbackRoute: ApiPublicOauthWhoopCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
